migliorata la formattazione del codice

diff --git a/bin/changedate b/bin/changedate
--- a/bin/changedate
+++ b/bin/changedate
@@ -1,91 +1,132 @@
 #!/bin/bash
-tput setaf 7 ; tput setab 4 ; tput bold ; printf '%33s%s%-12s\n' "Change expiration date" ; tput sgr0
+tput setaf 7
+tput setab 4
+tput bold
+printf '%33s%s%-12s\n' "Change expiration date"
+tput sgr0
 echo ""
-tput bold ; echo "User List and Expiration Dates:" ; tput sgr0
+tput bold
+echo "User List and Expiration Dates:"
+tput sgr0
 echo ""
-tput setaf 3 ; tput bold 
-awk -F : '$3 >= 500 { print $1 }' /etc/passwd | grep -v '^nobody' | while read user
-  do
+tput setaf 3
+tput bold
+awk -F : '$3 >= 500 { print $1 }' /etc/passwd | grep -v '^nobody' | while read user; do
 	expire="$(chage -l $user | grep -E "Account expires" | cut -d ' ' -f3-)"
-	if [[ $expire == "never" ]]
-	then
+	if [[ $expire == "never" ]]; then
 		nunca="Nunca"
 		printf '  %-30s%s\n' "$user" "Nunca"
 	else
 		databr="$(date -d "$expire" +"%Y%m%d")"
 		hoje="$(date -d today +"%Y%m%d")"
-		if [ $hoje -ge $databr ]
-		then
+		if [ $hoje -ge $databr ]; then
 			datanormal="$(date -d"$expire" '+%d/%m/%Y')"
-			printf '  %-30s%s' "$user" "$datanormal" ; tput setaf 1 ; tput bold ; echo " (Expirado)" ; tput setaf 3
-			echo "exp" > /tmp/exp
+			printf '  %-30s%s' "$user" "$datanormal"
+			tput setaf 1
+			tput bold
+			echo " (Expirado)"
+			tput setaf 3
+			echo "exp" >/tmp/exp
 		else
 			datanormal="$(date -d"$expire" '+%d/%m/%Y')"
 			printf '  %-30s%s\n' "$user" "$datanormal"
 		fi
 	fi
-  done
+done
 tput sgr0
 echo ""
-if [ -a /tmp/exp ]
-then
-	tput setaf 2 ; tput bold ; echo "To remove all expired users use the command: expcleaner " ; echo "" ; tput sgr0
+if [ -a /tmp/exp ]; then
+	tput setaf 2
+	tput bold
+	echo "To remove all expired users use the command: expcleaner "
+	echo ""
+	tput sgr0
 	rm /tmp/exp
 fi
 read -p "Username to change expiration date: " usuario
-if [[ -z $usuario ]]
-then
+if [[ -z $usuario ]]; then
 	echo ""
-	tput setaf 7 ; tput setab 4 ; tput bold ; echo "You entered an empty or invalid username!" ; tput sgr0
+	tput setaf 7
+	tput setab 4
+	tput bold
+	echo "You entered an empty or invalid username!"
+	tput sgr0
 	echo ""
 	exit 1
 else
-	if [[ `grep -c /$usuario: /etc/passwd` -ne 0 ]]
-	then
+	if [[ $(grep -c /$usuario: /etc/passwd) -ne 0 ]]; then
 		read -p "Digite uma nova data de expiração (DIA/MÊS/ANO): " inputdate
 		sysdate="$(echo "$inputdate" | awk -v FS=/ -v OFS=- '{print $3,$2,$1}')"
-		if (date "+%Y-%m-%d" -d "$sysdate" > /dev/null  2>&1)
-		then
-			if [[ -z $inputdate ]]
-			then
+		if (date "+%Y-%m-%d" -d "$sysdate" >/dev/null 2>&1); then
+			if [[ -z $inputdate ]]; then
 				echo ""
-				tput setaf 7 ; tput setab 4 ; tput bold ;	echo "You entered an invalid or nonexistent date! "; echo " Please enter a valid date in DAY / MONTH / YEAR format" ; echo "For example: 21/04/2018" ; tput sgr0
+				tput setaf 7
+				tput setab 4
+				tput bold
+				echo "You entered an invalid or nonexistent date! "
+				echo " Please enter a valid date in DAY / MONTH / YEAR format"
+				echo "For example: 21/04/2018"
+				tput sgr0
 				echo ""
-				exit 1	
+				exit 1
 			else
-				if (echo $inputdate | egrep [^a-zA-Z] &> /dev/null)
-				then
+				if (echo $inputdate | egrep [^a-zA-Z] &>/dev/null); then
 					today="$(date -d today +"%Y%m%d")"
 					timemachine="$(date -d "$sysdate" +"%Y%m%d")"
-					if [ $today -ge $timemachine ]
-					then
+					if [ $today -ge $timemachine ]; then
 						echo ""
-						tput setaf 7 ; tput setab 4 ; tput bold ;	echo "You entered a past date or the current day! "; echo " Please enter a valid future date in DAY / MONTH / YEAR format" ; echo "for example: 21/04/2018" ; tput sgr0
+						tput setaf 7
+						tput setab 4
+						tput bold
+						echo "You entered a past date or the current day! "
+						echo " Please enter a valid future date in DAY / MONTH / YEAR format"
+						echo "for example: 21/04/2018"
+						tput sgr0
 						echo ""
 						exit 1
 					else
 						chage -E $sysdate $usuario
 						echo ""
-						tput setaf 7 ; tput setab 1 ; tput bold ; echo "Expiration date for user $usuario changed to: $inputdate" ; tput sgr0
+						tput setaf 7
+						tput setab 1
+						tput bold
+						echo "Expiration date for user $usuario changed to: $inputdate"
+						tput sgr0
 						echo ""
 						exit 1
 					fi
 				else
 					echo ""
-					tput setaf 7 ; tput setab 4 ; tput bold ;	echo "You entered an invalid or nonexistent date!" ; echo " Please enter a valid future date in DAY / MONTH / YEAR format" ; echo "for example: 21/04/2018" ; tput sgr0
+					tput setaf 7
+					tput setab 4
+					tput bold
+					echo "You entered an invalid or nonexistent date!"
+					echo " Please enter a valid future date in DAY / MONTH / YEAR format"
+					echo "for example: 21/04/2018"
+					tput sgr0
 					echo ""
 					exit 1
 				fi
 			fi
 		else
 			echo ""
-			tput setaf 7 ; tput setab 4 ; tput bold ;	echo "You entered an invalid or nonexistent date!" ; echo " Please enter a valid future date in DAY / MONTH / YEAR format" ; echo "for example: 21/04/2018" ; tput sgr0
+			tput setaf 7
+			tput setab 4
+			tput bold
+			echo "You entered an invalid or nonexistent date!"
+			echo " Please enter a valid future date in DAY / MONTH / YEAR format"
+			echo "for example: 21/04/2018"
+			tput sgr0
 			echo ""
 			exit 1
 		fi
 	else
 		echo " "
-		tput setaf 7 ; tput setab 4 ; tput bold ;	echo "User $usuario does not exists!" ; tput sgr0
+		tput setaf 7
+		tput setab 4
+		tput bold
+		echo "User $usuario does not exists!"
+		tput sgr0
 		echo " "
 		exit 1
 	fi
diff --git a/bin/deletehost b/bin/deletehost
--- a/bin/deletehost
+++ b/bin/deletehost
@@ -1,34 +1,76 @@
 #!/bin/bash
 payload="/etc/squid3/payload.txt"
-tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-10s\n' "Delete Squid3 host" ; tput sgr0
-if [ ! -f "$payload" ]
-then
-	tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "$payload not found" ; tput sgr0
+tput setaf 7
+tput setab 4
+tput bold
+printf '%35s%s%-10s\n' "Delete Squid3 host"
+tput sgr0
+if [ ! -f "$payload" ]; then
+	tput setaf 7
+	tput setab 4
+	tput bold
+	echo ""
+	echo "$payload not found"
+	tput sgr0
 	exit 1
 else
-	tput setaf 2 ; tput bold ; echo ""; echo "Current Domains in File $payload:" ; tput sgr0
-	tput setaf 3 ; tput bold ; echo "" ; cat $payload ; echo "" ; tput sgr0
+	tput setaf 2
+	tput bold
+	echo ""
+	echo "Current Domains in File $payload:"
+	tput sgr0
+	tput setaf 3
+	tput bold
+	echo ""
+	cat $payload
+	echo ""
+	tput sgr0
 	read -p "Enter the domain you want to remove from the list:" host
-	if [[ -z $host ]]
-		then
-			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "You entered an empty or non-existent domain!" ; echo "" ; tput sgr0
+	if [[ -z $host ]]; then
+		tput setaf 7
+		tput setab 4
+		tput bold
+		echo ""
+		echo "You entered an empty or non-existent domain!"
+		echo ""
+		tput sgr0
+		exit 1
+	else
+		if [[ $(grep -c "^$host" $payload) -ne 1 ]]; then
+			tput setaf 7
+			tput setab 4
+			tput bold
+			echo ""
+			echo "Domain $host not found in $payload"
+			echo ""
+			tput sgr0
 			exit 1
 		else
-		if [[ `grep -c "^$host" $payload` -ne 1 ]]
-		then
-			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Domain $host not found in $payload" ; echo "" ; tput sgr0
-			exit 1
-		else
-			grep -v "^$host" $payload > /tmp/a && mv /tmp/a $payload
-			tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "$payload file updated, domain was successfully removed:" ; tput sgr0
-			tput setaf 3 ; tput bold ; echo "" ; cat $payload ; echo "" ; tput sgr0
-			if [ ! -f "/etc/init.d/squid3" ]
-			then
+			grep -v "^$host" $payload >/tmp/a && mv /tmp/a $payload
+			tput setaf 7
+			tput setab 1
+			tput bold
+			echo ""
+			echo "$payload file updated, domain was successfully removed:"
+			tput sgr0
+			tput setaf 3
+			tput bold
+			echo ""
+			cat $payload
+			echo ""
+			tput sgr0
+			if [ ! -f "/etc/init.d/squid3" ]; then
 				service squid3 reload
 			else
 				/etc/init.d/squid3 reload
-			fi	
-			tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Squid3 Proxy has been successfully reloaded!" ; echo "" ; tput sgr0
+			fi
+			tput setaf 7
+			tput setab 1
+			tput bold
+			echo ""
+			echo "Squid3 Proxy has been successfully reloaded!"
+			echo ""
+			tput sgr0
 			exit 1
 		fi
 	fi
